<?php
// send_reminder.php - send email reminders via PHP mail()
session_start(); // Start session for CSRF token access

include './connect-DB.php';

// Enable error reporting for debugging
ini_set('display_errors', 1);
error_reporting(E_ALL);

if (isset($_POST['sendReminder'])) {
    // Verify CSRF token
    if (!isset($_POST['csrf_token']) || !isset($_SESSION['csrf_token_list_forms']) || !hash_equals($_SESSION['csrf_token_list_forms'], $_POST['csrf_token'])) {
        die("CSRF token validation failed for send reminder.");
    }
    // It's good practice to use the token once, but for list forms that might refresh
    // or allow multiple actions, regeneration might be too aggressive or needs careful handling.
    // For now, we won't regenerate it here to allow multiple reminders from the same page load.
    // If page reloads, a new token would be generated by portal.php anyway.

    $id = htmlspecialchars($_POST['pmk']);

    // Fetch bill details
    $stmt = $pdo->prepare(
        'SELECT fldDue, fldOwe, fldItem, fldTotal, fldCost
         FROM tblUtilities WHERE pmkBillID = ?'
    );
    $stmt->execute([$id]);
    $bill = $stmt->fetch(PDO::FETCH_ASSOC);

    if ($bill) {
        $due = $bill['fldDue'];
        $item = $bill['fldItem'];
        $total = $bill['fldTotal'];
        $cost = $bill['fldCost'];

        $owedList = array_map('trim', explode(',', $bill['fldOwe']));

        // Map names to email addresses
        $emailMap = [
            'Aaron' => 'aperkel@uvm.edu',
            'Owen' => 'oacook@uvm.edu',
            'Ben' => 'bquacken@uvm.edu',
        ];

        // Determine subject urgency based on due date
        $dueDate = new DateTime($due);
        $today = new DateTime();
        $interval = $today->diff($dueDate)->days;
        $subject = ($interval <= 3)
            ? 'URGENT: Utility Bill Reminder'
            : 'Utility Bill Reminder';

        // Prepare email headers
        $headers = "MIME-Version: 1.0\r\n";
        $headers .= "Content-type: text/html; charset=UTF-8\r\n";
        $headers .= "From: 81 Buell Utilities <me@aaronperkel.com>\r\n";

        $sentRecipients = [];
        foreach ($owedList as $name) {
            if (empty($name) || !isset($emailMap[$name])) {
                continue;
            }
            $to = $emailMap[$name];
            $sentRecipients[] = $to;

            // Build the new “db.py–style” body
            $body = <<<HTML
                <p style="font: 14pt serif;">Hello {$name},</p>
                <p style="font: 14pt serif;">This is a reminder that your <strong>{$item}</strong> bill is due soon.</p>
                <ul>
                <li style="font: 14pt serif;">Bill total: \${$total}</li>
                <li style="font: 14pt serif;">Cost per person: \${$cost}</li>
                </ul>
                <p style="font: 14pt serif;">
                    Please login to
                    <a href="https://utilities.aperkel.w3.uvm.edu">81 Buell Utilities</a>
                    for more info.
                </p>
                <p style="font: 14pt serif;">
                    <span style="color: green;">81 Buell Utilities</span><br>
                    P: (478)262-8935 | E: me@aaronperkel.com
                </p>
                HTML;

            mail($to, $subject, $body, $headers);
        }

        // ——— now send yourself a confirmation ———
        $confirmTo = 'aperkel@uvm.edu';
        $confirmSubj = 'Mail Sent';
        $sentList = implode(', ', $sentRecipients);
        $confirmBody = <<<HTML
            <p style="font: 12pt monospace;">An email was just sent via utilities.aperkel.w3.uvm.edu.</p>
            <hr>
            <p style="font: 12pt monospace;">To: {$sentList}<br>
            <p style="font: 12pt monospace;">Subject: {$subject}</p>
            HTML;

        mail($confirmTo, $confirmSubj, $confirmBody, $headers);
    }

    // Redirect back
    header('Location: ' . $_SERVER['HTTP_REFERER']);
    exit;
}
?>